## Exploração das bases de dados

### Tabela: order_review_dataset

In [2]:
from pathlib import Path
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [7]:
df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [8]:
df.tail()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [7]:
print(f"Linhas: {df.shape[0]:,}")
print(f"Colunas: {df.shape[1]}")

Linhas: 99,224
Colunas: 7

In [12]:
df.dtypes

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [14]:
df.isna().sum().sort_values(ascending=False)

review_comment_title       87656
review_comment_message     58247
review_id                      0
review_score                   0
order_id                       0
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [15]:
df.nunique().sort_values(ascending=False)

order_id                   98673
review_id                  98410
review_answer_timestamp    98248
review_comment_message     36159
review_comment_title        4527
review_creation_date         636
review_score                   5
dtype: int64

In [16]:
df["order_id"].value_counts().gt(1).sum()

np.int64(547)

In [18]:
df["order_id"].value_counts().value_counts().sort_index()

count
1    98126
2      543
3        4
Name: count, dtype: int64

In [17]:
pedidos_multiplas = df["order_id"].value_counts()
pedidos_multiplas = pedidos_multiplas[pedidos_multiplas > 1].index

df[df["order_id"].isin(pedidos_multiplas)].sort_values("order_id")

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
22423,2a74b0559eb58fc1ff842ecc999594cb,0035246a40f520710769010f752e7507,5,NaN,Estou acostumada a comprar produtos pelo barat...,2017-08-25 00:00:00,2017-08-29 21:45:57
25612,89a02c45c340aeeb1354a24e7d4b2c1e,0035246a40f520710769010f752e7507,5,NaN,NaN,2017-08-29 00:00:00,2017-08-30 01:59:12
22779,ab30810c29da5da8045216f0f62652a2,013056cfe49763c6f66bda03396c5ee3,5,NaN,NaN,2018-02-22 00:00:00,2018-02-23 12:12:30
68633,73413b847f63e02bc752b364f6d05ee9,013056cfe49763c6f66bda03396c5ee3,4,NaN,NaN,2018-03-04 00:00:00,2018-03-05 17:02:00
854,830636803620cdf8b6ffaf1b2f6e92b2,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:06
...,...,...,...,...,...,...,...
94504,c56a88a404315a0d9e412c1472dda2c4,ff763b73e473d03c321bcd5a053316e8,5,NaN,NaN,2017-11-01 00:00:00,2017-11-01 19:55:52
18783,80f25f32c00540d49d57796fb6658535,ff850ba359507b996e8b2fbb26df8d03,5,NaN,"Envio rapido, produto conforme descrito no anu...",2017-08-22 00:00:00,2017-08-25 11:40:22
41355,39de8ad3a1a494fc68cc2d5382f052f4,ff850ba359507b996e8b2fbb26df8d03,5,NaN,Envio rapido... Produto 100%,2017-08-16 00:00:00,2017-08-17 11:56:55
53962,5476dd0eaee7c4e2725cafb011aa758c,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-21 13:24:55
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16

In [20]:
df["review_id"].value_counts().value_counts().sort_index()

count
1    97621
2      764
3       25
Name: count, dtype: int64

In [22]:
review_multiplas = df["review_id"].value_counts()
review_multiplas = review_multiplas[review_multiplas > 2].index

df[df["review_id"].isin(review_multiplas)].sort_values("review_id")

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
8404,08528f70f579f0c830189efc523d2182,7813842ae95e8c497fc0233232ae815a,1,Produto errado,Entrega do produto diferente do solicitado\r\n...,2018-08-03 00:00:00,2018-08-06 00:09:52
39950,08528f70f579f0c830189efc523d2182,03310aa823a66056268a3bab36e827fb,1,Produto errado,Entrega do produto diferente do solicitado\r\n...,2018-08-03 00:00:00,2018-08-06 00:09:52
74820,08528f70f579f0c830189efc523d2182,53c71d3953507c6239ff73917ed358c9,1,Produto errado,Entrega do produto diferente do solicitado\r\n...,2018-08-03 00:00:00,2018-08-06 00:09:52
20646,0c76e7a547a531e7bf9f0b99cba071c1,3525e0e57f9d276d522d570bd46cb39c,5,NaN,NaN,2017-08-31 00:00:00,2017-09-05 15:27:17
33629,0c76e7a547a531e7bf9f0b99cba071c1,98c977c116f7779360e9fecffd3860b6,5,NaN,NaN,2017-08-31 00:00:00,2017-09-05 15:27:17
...,...,...,...,...,...,...,...
48239,e44840754f12fad2b8646712121b349a,57cc72d3e635bf57199d76328279b875,4,NaN,NaN,2017-11-01 00:00:00,2017-11-02 00:11:06
90552,e44840754f12fad2b8646712121b349a,6ceabf34d230c31f161988dd2ff8fa92,4,NaN,NaN,2017-11-01 00:00:00,2017-11-02 00:11:06
11595,f4bb9d6dd4fb6dcc2298f0e7b17b8e1e,7791eb26e081ed5f8dd15b40c45393a3,4,NaN,NaN,2018-03-29 00:00:00,2018-03-30 00:29:09
51527,f4bb9d6dd4fb6dcc2298f0e7b17b8e1e,03c939fd7fd3b38f8485a0f95798f1f6,4,NaN,NaN,2018-03-29 00:00:00,2018-03-30 00:29:09
76613,f4bb9d6dd4fb6dcc2298f0e7b17b8e1e,9dc9cfe8dd61f0e37b0baa3043517059,4,NaN,NaN,2018-03-29 00:00:00,2018-03-30 00:29:09

In [54]:
# Quantas vezes cada order_id e review_id aparecem
contagem = df.groupby(
    ["order_id", "review_id"]
).size().reset_index(name="quantidade_registros")

# Quantidade de vezes que cada order_id aparece
contagem["qtd_order_id"] = contagem["order_id"].map(
    df["order_id"].value_counts()
)

# Quantidade de vezes que cada review_id aparece
contagem["qtd_review_id"] = contagem["review_id"].map(
    df["review_id"].value_counts()
)

# Resumo das combinações
resumo = (
    contagem.groupby(["qtd_order_id", "qtd_review_id"])
    .size()
    .reset_index(name="quantidade_combinacoes")
    .sort_values(["qtd_order_id", "qtd_review_id"])
)

display(resumo)

   qtd_order_id  qtd_review_id  quantidade_combinacoes
0             1              1                   97172
1             1              2                     909
2             1              3                      45
3             2              1                     444
4             2              2                     615
5             2              3                      27
6             3              1                       5
7             3              2                       4
8             3              3                       3

### Tabela: olist_orders_dataset

In [4]:
df_orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [25]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [35]:
print(f"Linhas: {df_orders.shape[0]:,}")
print(f"Colunas: {df_orders.shape[1]}")

Linhas: 99,441
Colunas: 8

In [26]:
df_orders.isna().sum().sort_values(ascending=False)

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
order_id                            0
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_estimated_delivery_date       0
dtype: int64

In [55]:
df_orders.nunique().sort_values(ascending=False)

order_id                         99441
customer_id                      99441
order_purchase_timestamp         98875
order_delivered_customer_date    95664
order_approved_at                90733
order_delivered_carrier_date     81018
order_estimated_delivery_date      459
order_status                         8
dtype: int64

In [34]:
display(df_orders["order_status"].unique())

<ArrowStringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [43]:
df_orders.groupby("order_status")["order_id"].nunique().sort_values(ascending=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_id, dtype: int64

In [37]:
df_orders[df_orders["order_delivered_customer_date"].isna()].groupby("order_status")["order_id"].nunique().sort_values(ascending=False)

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: order_id, dtype: int64

In [38]:
df_orders[df_orders["order_delivered_carrier_date"].isna()].groupby("order_status")["order_id"].nunique().sort_values(ascending=False)

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: order_id, dtype: int64

In [39]:
df_orders[df_orders["order_approved_at"].isna()].groupby("order_status")["order_id"].nunique().sort_values(ascending=False)

order_status
canceled     141
delivered     14
created        5
Name: order_id, dtype: int64

### Explorando a intersecção entre tabelas

In [57]:
df_orders.loc[
    df_orders["order_id"].isin(df["order_id"]),
    "order_id"
].nunique()

98673

In [58]:
df_orders.loc[
    ~df_orders["order_id"].isin(df["order_id"]),
    "order_id"
].nunique()

768

In [60]:
df_orders.loc[
    ~df_orders["order_id"].isin(df["order_id"])
].groupby("order_status")["order_id"].nunique().sort_values(ascending=False)

order_status
delivered      646
shipped         75
canceled        20
unavailable     14
processing       6
invoiced         5
created          2
Name: order_id, dtype: int64

In [59]:
df.loc[
    ~df["order_id"].isin(df_orders["order_id"]),
    "order_id"
].nunique()

0

In [80]:
df_orders.loc[
    df_orders["order_id"].isin(
        df.loc[
            df["review_comment_message"].isna()
            | df["review_comment_message"].str.strip().eq(""),
            "order_id"
        ]
    ),
    "order_id"
].nunique()

57969

In [42]:
ids = [
    "7813842ae95e8c497fc0233232ae815a",
    "03310aa823a66056268a3bab36e827fb",
    "53c71d3953507c6239ff73917ed358c9"
]

df[df["order_id"].isin(ids)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
8404,08528f70f579f0c830189efc523d2182,7813842ae95e8c497fc0233232ae815a,1,Produto errado,Entrega do produto diferente do solicitado\r\n...,2018-08-03 00:00:00,2018-08-06 00:09:52
39950,08528f70f579f0c830189efc523d2182,03310aa823a66056268a3bab36e827fb,1,Produto errado,Entrega do produto diferente do solicitado\r\n...,2018-08-03 00:00:00,2018-08-06 00:09:52
74820,08528f70f579f0c830189efc523d2182,53c71d3953507c6239ff73917ed358c9,1,Produto errado,Entrega do produto diferente do solicitado\r\n...,2018-08-03 00:00:00,2018-08-06 00:09:52

In [41]:
ids = [
    "7813842ae95e8c497fc0233232ae815a",
    "03310aa823a66056268a3bab36e827fb",
    "53c71d3953507c6239ff73917ed358c9"
]

df_orders[df_orders["order_id"].isin(ids)]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3684,03310aa823a66056268a3bab36e827fb,25dbbf0c477fd4ae0880aaffbb12e8b3,canceled,2018-08-07 16:33:59,NaN,NaN,NaN,2018-09-04 00:00:00
37498,53c71d3953507c6239ff73917ed358c9,26dcb450c4b5b390e79e6d5d0f2c6535,delivered,2018-07-24 20:41:01,2018-07-24 20:55:31,2018-07-27 15:24:00,2018-08-02 18:41:16,2018-08-21 00:00:00
95451,7813842ae95e8c497fc0233232ae815a,040d94f8ba8ca26014bd6f7e8a6e0c0d,canceled,2018-08-17 20:06:36,NaN,NaN,NaN,2018-09-17 00:00:00

In [44]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Contar pedidos únicos por status
df_orders[df_orders["order_id"].isin(pedidos_uma_review)] \
    .groupby("order_status")["order_id"] \
    .nunique() \
    .sort_values(ascending=False)

order_status
delivered      95307
shipped         1021
canceled         601
unavailable      593
invoiced         305
processing       294
created            3
approved           2
Name: order_id, dtype: int64

In [ ]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_shipped = df_orders.loc[
    (df_orders["order_status"] == "shipped") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_shipped)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
4345,c49ed188fdeaa694f0bddb9d78b1a718,6147a4d49752afd35a119d794e481588,3,NaN,NaN,2017-05-31 00:00:00,2017-06-02 11:32:38
6004,4bbd26c22370d9ceeb45fc685ee15d63,f373335aac9a659de916f7170b8bc07a,2,NaN,não recebi o produto consta que o mesmo voltou...,2018-04-15 00:00:00,2018-04-19 01:31:04
17489,5853e27c64b89e222c5e4edf78bec3d4,ee64d42b8cf066f35eac1cf57de1aa85,1,NaN,NaN,2018-07-01 00:00:00,2018-07-11 20:41:18
29556,3702eff31f779fd92452831a751d4201,10918fe4d665fda80034712895c2b92f,1,NaN,NaN,2017-08-05 00:00:00,2017-08-05 15:32:13
30812,bf8ad702d153b8c1c73328591242c7d1,3b4ad687e7e5190db827e1ae5a8989dd,1,NaN,Comprei um produto e não entregaram. \r\nPedi ...,2018-08-05 00:00:00,2018-08-05 13:47:00
33298,8bc9fc3e9fa62ffd285a1f5190932176,4d630f57194f5aba1a3d12ce23e71cd9,3,NaN,NaN,2017-12-16 00:00:00,2017-12-20 09:34:26
70816,a205cb50c298eea221ae32dc498db2c3,36530871a5e80138db53bcfd8a104d90,1,NaN,NaN,2017-06-14 00:00:00,2017-06-16 12:13:47
75439,dde1e40541d41f6ef8b16aec2913338c,b68d69564a79dea4776afa33d1d2fcab,1,NaN,Não chegou.,2018-03-25 00:00:00,2018-03-25 03:41:01
85047,d37b8cfe7008f4c4d72e4b441a827cf9,95e42e6aaf6264cd3e77c06b32dc3003,1,NaN,Nao entregaram o produto e nao entraram em con...,2017-12-10 00:00:00,2017-12-11 23:23:27
85534,4221f3f3b5ffcf57d8eb3497d3332479,5869074071e0f56e9085dc3742c97b2a,1,Péssima muito Ruin,\r\n,2018-07-05 00:00:00,2018-07-05 11:56:39

In [47]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_canceled = df_orders.loc[
    (df_orders["order_status"] == "canceled") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_canceled)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
5405,a47832fc905918220d6e1a9642bbd0eb,0966b61e30c4a07edbd7523f59b3f3e4,1,Não recebi o produto,Comprei o produto e depois eles informaram que...,2018-07-05 00:00:00,2018-07-05 12:35:40
9020,9c0d840dfe562debfa52a1792bd64bff,00b1cb0320190ca0daa2c88b35206009,1,Entregaram produto errado,Comprei dois fones de ouvido com valor de R$ 5...,2018-08-28 00:00:00,2018-08-28 18:25:55
24260,d15ec7fbf73d246a918e3bf1a7e5f268,df8282afe61008dc26c6c31011474d02,3,NaN,Razoável,2017-04-12 00:00:00,2017-04-12 14:18:26
48750,fe270df00abcb5c39fc7385143a12167,a39d3db795a5cf4c8b6c9dd050f0d326,1,NaN,"Comprei o produto e não foi entregue, o prazo ...",2017-04-01 00:00:00,2017-04-03 12:49:21
66680,6e4344680dbd30c75f78394e0dcfffdf,ed3efbd3a87bea76c2812c66a0b32219,2,NaN,O produto veio com defeito ele não liga não fu...,2018-07-28 00:00:00,2018-07-30 11:06:16
71138,fda38b7c98f571ef4c6da9eba2b417c6,7a9d4c7f9b068337875b95465330f2fc,5,NaN,NaN,2017-06-01 00:00:00,2017-06-01 08:21:44
72781,15c8f3b3ff412d0f8d6b72053335fd0b,3a129877493c8189c59c60eb71d97c29,1,NaN,Não recebi o produto e também não tive reembolso,2018-02-25 00:00:00,2018-02-25 11:02:38
86885,02684930e50680f1b2105cb0ccfae932,9021cf1919f615a121410790dcce848f,1,NaN,Não recebi e espero receber,2018-08-26 00:00:00,2018-08-26 20:23:54
89159,14d540de5632307e389e9416086fc978,1b9ecfe83cdc259250e1a8aca174f0ad,1,NaN,NaN,2018-08-17 00:00:00,2018-08-19 13:51:01
92382,0f54fea9e89c2a9398b2bd56e3880eda,8d4c637f1accf7a88a4555f02741e606,5,Adorei,NaN,2018-08-26 00:00:00,2018-08-26 20:21:38

In [49]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_unavailable = df_orders.loc[
    (df_orders["order_status"] == "unavailable") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_unavailable)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
3664,5ac796e8c64e828de2c229ca7067980f,6ad57aecbae806a7e9cc2cdb6b380711,1,NaN,Estou esperando até agora a entrega do produto...,2017-12-31 00:00:00,2017-12-31 13:00:06
17108,63dfe8abe264cea1ff8708e7057b37d9,9f3458f0433d4cfa472f4682654b8d49,5,NaN,Embora não tenha recebido a mercadoria por não...,2017-08-11 00:00:00,2017-08-14 13:04:29
25534,519e62c42f33dce5b47ffddf9fde28df,d57e15fb07fd180f06ab3926b39edcd2,1,NaN,Não compre,2018-02-09 00:00:00,2018-02-09 03:22:43
49887,44c6d194170df31929a4ab4b7ae8512a,2f634e2cebf8c0283e7ef0989f77d217,1,NaN,"Comprei um perfume Bleu de Chanel , paguei e n...",2017-10-29 00:00:00,2017-10-29 16:40:21
51136,aaeb804fe1828db8cc3d8b52ec38a1fa,37553832a3a89c9b2db59701c357ca67,1,NaN,Até hoje não recebi meu produto e nem uma resp...,2017-09-10 00:00:00,2017-09-12 17:00:15
52144,b6ea5566d6060db04ebe53a1291e4541,c272bcd21c287498b4883c7512019702,3,NaN,NaN,2018-02-18 00:00:00,2018-02-20 19:23:56
54700,3e676449a927e393760c598df0bd7e7b,ee0db22a8e742b752914016708470ec8,1,NaN,"voces se tornaram corruptos,paguei e ainda nao...",2017-09-20 00:00:00,2017-10-10 21:22:12
60947,7fb04ba6e8b915c62557517d5c1e04ee,8e24261a7e58791d10cb1bf9da94df5c,1,NaN,Anunciam um produto que não tem em estoque e a...,2017-12-07 00:00:00,2017-12-11 10:37:57
73513,fa176e56fff4c6d5a9f58d4e735e3ab3,86f0bcd9b426a2c1022ae317c7f27be6,4,NaN,NaN,2017-03-31 00:00:00,2017-04-02 13:25:58
86208,16c9343b992649ddef0e1ea14ab26f63,f0df036e9be21fc238f131bbfcdde769,1,NaN,NaN,2017-04-09 00:00:00,2017-04-09 15:11:16

In [52]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_invoiced = df_orders.loc[
    (df_orders["order_status"] == "invoiced") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_invoiced)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
26784,e4732f13c7a91d3c6ff8daa4d43c6eb3,f029d5966aa03c87e17e2482f86202b1,1,NaN,Não recebi o produto até hj \r\nEstão dizendo ...,2017-11-16 00:00:00,2017-11-19 16:42:39
27226,0e2db9f3094b64e23c8cef7a3b6fb88b,38b7efdf33dd5561f4f5d4f6e07b0414,1,NaN,Meu produto não chegou. Isso gerou estresse e ...,2017-08-30 00:00:00,2017-09-04 12:33:47
28656,e07549ef5311abcc92ba1784b093fb56,136cce7faa42fdb2cefd53fdc79a6098,2,NaN,fiquei triste por n ter me atendido.,2017-05-13 00:00:00,2017-05-13 20:25:42
37584,201c8292d23f777d7112e1cc763a455c,c3a6dc9afef5794ea4a867b5a18e0ad1,1,NaN,o produto nao foi entregue,2017-12-20 00:00:00,2017-12-20 12:21:09
41914,ebbc2bf171b8517901800e1aab9dc442,6a828279d73f18174dd3b9c653d5213d,1,NaN,Nao recebi meu produto,2017-07-16 00:00:00,2017-07-16 11:04:23
56909,3efebd3f541f29c580265cfc6bfbd0e8,566c5bff1142c9d6003a83fd2e8ad1e5,1,NaN,"Não recebi nem receberei minha compra, gostari...",2017-12-19 00:00:00,2017-12-22 13:47:48
59980,f2a479207e94403d6a05045c65356ce1,b4c9f083bce61caf47fb38f9ba058bce,5,NaN,O pedido foi cancelado por mim.,2017-09-01 00:00:00,2017-09-01 08:11:37
72689,4864d0574f90b31c8973b246d7154781,51b0dccc8596ce37a930dff2d63a10a2,3,NaN,NaN,2017-06-08 00:00:00,2017-06-08 13:09:45
76353,c4b17a374b71539eb360fe5baaa9a10e,0760a852e4e9d89eb77bf631eaaf1c84,3,bolo fake,"Gostei do produto, porem fiquei preocupada não...",2018-08-25 00:00:00,2018-08-29 10:48:52
94709,ddf12e9921f5ea99f6ce41d06fc4ee7d,5504eaa5a86eb25fa666cf2e6b96c701,1,NaN,não recomendo,2017-12-21 00:00:00,2017-12-23 11:03:03

In [53]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_processing= df_orders.loc[
    (df_orders["order_status"] == "processing") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_processing)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
1626,8079a046b23b88c4cea485cfbd8aec39,15bed8e2fec7fdbadb186b57c46c92f2,5,NaN,NaN,2017-10-05 00:00:00,2017-10-05 12:55:11
10162,cdfb30d1ea8a715942969256b3567a3e,d815bd2c2bdd79e4c0e0263caa986d66,1,NaN,Infelizmente não recebi o produto solicitado e...,2017-04-19 00:00:00,2017-04-24 10:59:56
14746,18825455b8639598b4511791079ee332,1d52ba7197c7acebbb4f826f6585536f,1,NaN,Não recebi meu produto dentro do prazo e o ate...,2017-04-06 00:00:00,2017-04-06 06:23:38
43224,af37e86291b016d85be4b78f7782be5c,533e104c4193cf07d264603f7800fb71,1,NaN,Nao recebi o produto,2017-03-05 00:00:00,2017-03-07 04:32:40
47624,c7fb23cd8188e9ed9136d6b84ec117c6,6a6c7d523fd59eb5bbefc007331af717,1,NaN,estou aguardando o produto chegar,2017-12-21 00:00:00,2017-12-21 19:53:26
60831,160850927a5f16f903dc83a05e0a5826,d3c8851a6651eeff2f73b0e011ac45d0,1,NaN,NaN,2016-12-11 00:00:00,2016-12-13 10:17:32
62553,4afa6ec1d9e90e8a75288e372e6063b8,52b828f13e08788433adad4a7d135779,1,Entrega atrasada,Estou aguardando a entrega que já esta atrasada,2018-06-03 00:00:00,2018-06-04 11:52:09
69076,d9b59843977ca5abe27d874e48f84b06,745e1d4a7f8c4b548881788d4113bb1d,4,NaN,NaN,2017-12-15 00:00:00,2017-12-16 10:19:43
70078,3d4c7b99fec4c5b50207b2863e781e1c,4ea3508e2de6e58640c0efe3ef758829,1,NaN,Nunca tive problemas com esse site e no mesmo ...,2017-06-23 00:00:00,2017-06-23 13:15:15
73136,d1fe6e39e8ee198bd4bcbe694624e7fe,56ab0ef6726f49b711b84ce62e305c7c,1,NaN,Vendedor até agora não mando meu pedido,2017-12-16 00:00:00,2017-12-16 04:14:28

In [51]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_created = df_orders.loc[
    (df_orders["order_status"] == "created") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_created)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
31167,ce24a21f96199f7e7257d5346f387e5f,90ab3e7d52544ec7bc3363c82689965f,5,NaN,Embora o produto estivesse em falta a empresa ...,2017-12-06 00:00:00,2017-12-06 10:17:34
81521,64b53acf68ca2e45eebb01436a911982,7a4df5d8cff4090e541401a20a22bb80,1,NaN,NaN,2017-12-15 00:00:00,2017-12-15 13:33:49
91733,094b5d5ffff5d37b6195b4674ac84362,b5359909123fa03c50bdb0cfed07f098,1,NaN,o PRODUTO NÃO CHEGOU ATÉ HOJE.,2018-01-13 00:00:00,2018-01-14 23:15:02

In [50]:
# Identificar pedidos com exatamente uma avaliação
pedidos_uma_review = (
    df.groupby("order_id")
    .size()
    .loc[lambda x: x == 1]
    .index
)

# Selecionar alguns pedidos com status shipped
ids_approved = df_orders.loc[
    (df_orders["order_status"] == "approved") &
    (df_orders["order_id"].isin(pedidos_uma_review)),
    "order_id"
].head(10)

# Visualizar as avaliações desses pedidos
df[df["order_id"].isin(ids_approved)]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
65900,c9d705e0fcf5363bbcca93db2063c07f,132f1e724165a07f6362532bfb97486e,4,NaN,NaN,2017-05-24 00:00:00,2017-05-24 15:10:54
68177,624af81e4bae04a0f7a9d1440ecf0c4a,a2e4c44360b4a57bdff22f3a4630c173,1,NaN,NaN,2017-03-03 00:00:00,2017-03-13 22:27:45

### Base primária para RAG

Definiu-se que a base que será usada para o RAG seão de pedidos com avaliação diferente de NaN ou vazio, pois trazer NaN ou vazio para o fluxo não agregaria, todavia a nota dessas avaliações, bem como as outras informações serão importantes para o enriquecimento,

In [5]:
df_reviews_rag = df[
    df["review_comment_message"].notna()
    & df["review_comment_message"].str.strip().ne("")
].copy()

In [6]:
print("Total de registros:", len(df))
print("Registros selecionados:", len(df_reviews_rag))
print(
    "Pedidos únicos selecionados:",
    df_reviews_rag["order_id"].nunique()
)
print(
    "Reviews únicas selecionadas:",
    df_reviews_rag["review_id"].nunique()
)

Total de registros: 99224
Registros selecionados: 40950
Pedidos únicos selecionados: 40809
Reviews únicas selecionadas: 40641

In [8]:
import pandas as pd

# Identificar avaliações válidas
df_analise = df.copy()

df_analise["comentario_valido"] = (
    df_analise["review_comment_message"].notna()
    & df_analise["review_comment_message"].str.strip().ne("")
)

# Resumir as avaliações por pedido
pedidos = (
    df_analise
    .groupby("order_id")
    .agg(
        qtd_avaliacoes=("review_id", "count"),
        qtd_validas=("comentario_valido", "sum")
    )
    .reset_index()
)

# Classificar os pedidos
pedidos["classificacao"] = "Mais de uma avaliação e não válidas"

pedidos.loc[
    (pedidos["qtd_avaliacoes"] == 1)
    & (pedidos["qtd_validas"] == 1),
    "classificacao"
] = "Uma avaliação válida"

pedidos.loc[
    (pedidos["qtd_avaliacoes"] == 1)
    & (pedidos["qtd_validas"] == 0),
    "classificacao"
] = "Uma avaliação não válida"

pedidos.loc[
    (pedidos["qtd_avaliacoes"] > 1)
    & (pedidos["qtd_validas"] > 0),
    "classificacao"
] = "Mais de uma avaliação, com válidas"

# Exibir o volume de pedidos por categoria
resultado = (
    pedidos["classificacao"]
    .value_counts()
    .reindex(
        [
            "Uma avaliação válida",
            "Uma avaliação não válida",
            "Mais de uma avaliação, com válidas",
            "Mais de uma avaliação e não válidas"
        ],
        fill_value=0
    )
    .rename_axis("categoria")
    .reset_index(name="volume_pedidos")
)

display(resultado)

                             categoria  volume_pedidos
0                 Uma avaliação válida           40565
1             Uma avaliação não válida           57561
2   Mais de uma avaliação, com válidas             244
3  Mais de uma avaliação e não válidas             303

In [68]:
(df_reviews_rag["order_id"].value_counts() > 1).sum()

np.int64(140)

In [69]:
(df_reviews_rag["review_id"].value_counts() > 1).sum()

np.int64(299)

In [70]:
df_reviews_rag[["order_id", "review_id"]].isna().sum()

order_id     0
review_id    0
dtype: int64

In [71]:
print("Registros com comentário:", len(df_reviews_rag))
print("Pedidos únicos:", df_reviews_rag["order_id"].nunique())
print("Linhas excedentes:", len(df_reviews_rag) - df_reviews_rag["order_id"].nunique())

Registros com comentário: 40950
Pedidos únicos: 40809
Linhas excedentes: 141

In [81]:
df_reviews_rag["order_id"].value_counts().loc[lambda x: x > 1].value_counts().sort_index()

count
2    139
3      1
Name: count, dtype: int64

In [82]:
# Identificar pedidos com mais de uma linha
ids_duplicados = (
    df_reviews_rag["order_id"]
    .value_counts()
    .loc[lambda x: x > 1]
    .index
)

# Filtrar esses pedidos
df_pedidos_duplicados = df_reviews_rag[
    df_reviews_rag["order_id"].isin(ids_duplicados)
].copy()

# Contar pedidos com comentários iguais em todas as suas linhas
pedidos_com_comentarios_iguais = (
    df_pedidos_duplicados
    .groupby("order_id")["review_comment_message"]
    .nunique(dropna=False)
    .eq(1)
)

print(
    "Pedidos duplicados com comentários iguais:",
    pedidos_com_comentarios_iguais.sum()
)

Pedidos duplicados com comentários iguais: 14

In [83]:
df_pedidos_duplicados[
    df_pedidos_duplicados["order_id"].isin(
        pedidos_com_comentarios_iguais[
            pedidos_com_comentarios_iguais
        ].index
    )
].sort_values("order_id")[
    ["order_id", "review_id", "review_score", "review_comment_message"]
]

,order_id,review_id,review_score,review_comment_message
41299,195cdd5d4a7a7137487b3d3ab71c851f,be3f87c25a6a01b202bc0588a2e7b356,5,Entrega rápida.
86334,195cdd5d4a7a7137487b3d3ab71c851f,06bea893ab2998942039562a6b294c85,5,Entrega rápida.
29428,27dc874d0fc1a19c74ec77ca706be968,650f8208894144b97f95986628a224bf,5,chegou bem antes do prazo
54940,27dc874d0fc1a19c74ec77ca706be968,a56ae95ea4642e8951919ea3e3eddb91,5,chegou bem antes do prazo
50286,5525404ad9f5043e1164e6833b2c24ca,d6d5c4f6a64c5fccf2c3b7bbbe6143b2,4,bom
98331,5525404ad9f5043e1164e6833b2c24ca,a35901ae6fa34515bce25959b6219d6e,4,bom
15132,559d606ac642899e44550f194fec7e08,2172867fd5b1a55f98fe4608e1547b4b,5,Entrega no prazo e produto de qualidade!
24094,559d606ac642899e44550f194fec7e08,e26865c2fff514ba41fb9306ebe81054,5,Entrega no prazo e produto de qualidade!
28801,574c4ecf7699daffc21fc04eb876b8a8,7d35852d24f13f1afdc3ea193e943842,5,Muito bom
76991,574c4ecf7699daffc21fc04eb876b8a8,eb632ac43fa0e0b1455adde073a04d0f,5,Muito bom
36315,62bc181a6d897eba7057bb531ea5f094,5b5d6671a9a749006c26373a40707158,5,Exelente atendimento e entrega antes do prazo....
47421,62bc181a6d897eba7057bb531ea5f094,51f8d7ba9221dc818368c967e4beded3,5,Exelente atendimento e entrega antes do prazo....
5900,64f2e9aa85911b6a48e3d11ef05b73c7,34f483bf183f8b73aa2d672913bf2665,5,otimo
97369,64f2e9aa85911b6a48e3d11ef05b73c7,d4d5f3dcd2130a28d547b0ec78b2a707,5,otimo
15588,684497197738631cbe11c77e531a3220,727ff1d8d18233c42bf31211f90bf461,5,muito bom
73098,684497197738631cbe11c77e531a3220,61f661bb5dbec5b65d3bd6d63883c472,5,muito bom
9531,84aa61a900410cfe26b57337d376a1ae,471a7d853b152d77aefd43bc39f03d64,5,Recomendo!
42660,84aa61a900410cfe26b57337d376a1ae,1c481b7cc2949a1d699337f1bed766b0,5,Recomendo!
16951,94153bbf95f273c5b6c342d2acc6d017,1ef17c31c6a710e3cee7853fb387dcc3,5,Muito bom os produtos e foi entregs bem antes ...
59543,94153bbf95f273c5b6c342d2acc6d017,5660d7a94ecc8e9cbe8945bcfb06e764,5,Muito bom os produtos e foi entregs bem antes ...
83932,9e8bf3ebc81cc29ee6e934d95370e5bc,1ef17c31c6a710e3cee7853fb387dcc3,5,Muito bom os produtos e foi entregs bem antes ...
88590,9e8bf3ebc81cc29ee6e934d95370e5bc,13e2498580f7828386917cf4e6395a3e,5,Muito bom os produtos e foi entregs bem antes ...
33611,b48681f5e795989ee7e78953269720e2,5b5d6671a9a749006c26373a40707158,5,Exelente atendimento e entrega antes do prazo....
92746,b48681f5e795989ee7e78953269720e2,51f8d7ba9221dc818368c967e4beded3,5,Exelente atendimento e entrega antes do prazo....
52690,bc8446f693e6c406e28d5cee739dc4cd,2e809b95391bbfb7119a46b1a4df9508,4,Produto top pra quem que apaixonado por fazer ...
82095,bc8446f693e6c406e28d5cee739dc4cd,9282f8481d3fff93b5fc444eb5c934e2,4,Produto top pra quem que apaixonado por fazer ...
44535,f86e20fe6ce750c00d7ed08e8c67384f,9fc972bcf0b92cd6de83f1fcc4c90dc3,4,Satisfeita
71397,f86e20fe6ce750c00d7ed08e8c67384f,32fdac426bf6f97f7cbd250cff7f1ee8,5,Satisfeita

In [87]:
duplicados_comentario_nota = df_pedidos_duplicados[
    df_pedidos_duplicados.duplicated(
        subset=["order_id", "review_comment_message", "review_score"],
        keep=False
    )
].sort_values("order_id")


total_registros = len(duplicados_comentario_nota)

print(f"Total de registros: {total_registros}")

# Quantidade de pedidos afetados
total_pedidos = duplicados_comentario_nota["order_id"].nunique()

print(f"Total de pedidos: {total_pedidos}")

Total de registros: 26
Total de pedidos: 13